import { NextRequest } from 'next/server';
import { z } from 'zod';
import { withErrorHandler } from '@/lib/api/async-handler';
import { successResponse } from '@/lib/api/response';
import { requireAuth, Role } from '@/lib/auth/supabase-auth';
import { storageService } from '@/lib/storage/storage-service';
import { STORAGE_BUCKETS } from '@/lib/storage/buckets';
import { DEFAULT_SIGNED_URL_EXPIRY_SECONDS, MAX_SIGNED_URL_EXPIRY_SECONDS } from '@/lib/storage/signed-urls';
import { logAuditEventFromRequest } from '@/lib/audit/audit-logger';
import { uuidSchema } from '@/lib/validation/zod-helpers';
import { ForbiddenError } from '@/lib/errors/api-error';

const signedUrlRequestSchema = z
  .object({
    bucket: z.enum([STORAGE_BUCKETS.PRODUCT_IMAGES, STORAGE_BUCKETS.CUSTOM_ORDER_UPLOADS], {
      errorMap: () => ({
        message: `Bucket must be either '${STORAGE_BUCKETS.PRODUCT_IMAGES}' or '${STORAGE_BUCKETS.CUSTOM_ORDER_UPLOADS}'`,
      }),
    }),
    path: z
      .string()
      .min(1, 'Storage path is required')
      .max(500, 'Storage path exceeds maximum allowed length of 500 characters'),
    operation: z.enum(['upload', 'download'], {
      errorMap: () => ({ message: "Operation must be either 'upload' or 'download'" }),
    }),
    expiresIn: z
      .number()
      .int()
      .min(1, 'Expiry must be at least 1 second')
      .max(MAX_SIGNED_URL_EXPIRY_SECONDS, `Expiry cannot exceed ${MAX_SIGNED_URL_EXPIRY_SECONDS} seconds`)
      .default(DEFAULT_SIGNED_URL_EXPIRY_SECONDS),
    customOrderId: uuidSchema.optional(),
  })
  .strict();

type SignedUrlRequestInput = z.infer<typeof signedUrlRequestSchema>;

/**
 * POST /api/uploads/signed-url
 * Generates short-lived signed upload or download URLs for Supabase Storage.
 *
 * Security Controls:
 * - Server-side authentication (requireAuth)
 * - Strict Zod validation
 * - Public/Private bucket access isolation:
 *   - 'product-images': public read, admin-only upload
 *   - 'custom-order-uploads': private, owner + admin only
 * - Short expiry enforcement (default 60s, capped at 300s)
 * - Audit logging of signed URL generation
 */
export const POST = withErrorHandler(async (req: NextRequest, _context, requestId) => {
  const user = await requireAuth(req);
  const body = await req.json();
  const input = signedUrlRequestSchema.parse(body);

  let result: { signedUrl: string; expiresIn: number; path?: string; token?: string };

  if (input.operation === 'upload') {
    // Only administrators can upload to the product-images bucket or write to catalog/ paths
    if (
      (input.bucket === STORAGE_BUCKETS.PRODUCT_IMAGES ||
        input.path.toLowerCase().startsWith('catalog/') ||
        input.path.toLowerCase() === 'catalog') &&
      user.role !== Role.ADMIN
    ) {
      throw new ForbiddenError(
        'Access denied: Only atelier administrators can upload showcase images or write to catalog paths'
      );
    }

    let uploadPath = input.path;

    // For custom-order-uploads, the object path is ALWAYS generated by the server:
    // a cryptographically random UUID under a per-user folder (${user.id}/<uuid>.<ext>).
    // The server never trusts or accepts an arbitrary client-supplied path.
    if (input.bucket === STORAGE_BUCKETS.CUSTOM_ORDER_UPLOADS) {
      const dotIndex = input.path.lastIndexOf('.');
      const rawExt = dotIndex !== -1 ? input.path.substring(dotIndex).toLowerCase() : '.jpg';
      const safeExt = ['.jpg', '.jpeg', '.png', '.webp'].includes(rawExt)
        ? rawExt === '.jpeg'
          ? '.jpg'
          : rawExt
        : '.jpg';

      uploadPath = `custom-orders/${user.id}/${crypto.randomUUID()}${safeExt}`;
    }

    const uploadResult = await storageService.getSignedUploadUrl(user, {
      bucket: input.bucket,
      storagePath: uploadPath,
      expiresIn: input.expiresIn,
      customOrderId: input.customOrderId,
    });
    result = {
      ...uploadResult,
      path: uploadPath,
    };
  } else {
    const downloadResult = await storageService.getSignedDownloadUrl(user, {
      bucket: input.bucket,
      storagePath: input.path,
      expiresIn: input.expiresIn,
      customOrderId: input.customOrderId,
    });
    result = {
      ...downloadResult,
      path: input.path,
    };
  }

  await logAuditEventFromRequest(req, {
    actorId: user.id,
    action: `STORAGE_SIGNED_${input.operation.toUpperCase()}_URL_GENERATED`,
    entity: 'StorageObject',
    entityId: `${input.bucket}/${input.path}`,
    metadata: {
      bucket: input.bucket,
      path: input.path,
      operation: input.operation,
      expiresIn: input.expiresIn,
    },
  });

  return successResponse(result, requestId, {}, 200);
});
